**Basic Commands**

In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [2]:
print?

In [3]:
3+5

8

In [4]:
'hello' + ' ' + 'world'

'hello world'

In [5]:
x = [3, 4, 5] #this is a list
x

[3, 4, 5]

In [6]:
y = [4, 9, 7]
x+y #concatenation of lists

[3, 4, 5, 4, 9, 7]

**Numerical Python**

In [8]:
import numpy as np

In [9]:
x = np.array([3,4,5])
y = np.array([4,9,7])

In [10]:
x+y #not concatenation anymore

array([ 7, 13, 12])

This happens because in numpy we have matrices instead of lists, this was a sum of matrices

In [12]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
x.ndim

2

In [14]:
x.dtype

dtype('int64')

In [15]:
x = np.array([[1, 2], [3.0, 4]])
x

array([[1., 2.],
       [3., 4.]])

In [16]:
x.dtype

dtype('float64')

In [17]:
np.array?

In [18]:
np.array([[1,2], [3,4]], float).dtype

dtype('float64')

In [19]:
x.shape

(2, 2)

A *method* is a function associated with an object.

In [20]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [35]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2,3))
print('reshape x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshape x:
 [[1 2 3]
 [4 5 6]]


This output shows that numpy arrays are *row-oriented*, so, for example, (2,3) means 2 rows and 3 columns.

Observe that (2,3) is a *tuple*, not a list. The major difference between tuples and lists is that elements of tuples are immutable.

In [36]:
x_reshape[0, 0] #first element

1

In [37]:
x_reshape[1,2] #second row, third column element

6

In [38]:
print('x before we modify x_reshape: \n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)

x_reshape[0,0] = 5

print('x_reshape after we modify x_reshape:\n', x_reshape)
print('x after we modify x_reshape:\n', x)

x before we modify x_reshape: 
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify x_reshape:
 [[5 2 3]
 [4 5 6]]
x after we modify x_reshape:
 [5 2 3 4 5 6]


The reason that x changes, when we change x_reshape is because they occupy the same point in the memory. The line x_reshape = x.reshape((2,3)) does not creat a copy of x in a new shape, x_reshape points to the same spot in memory as x.

In [31]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2 #It is not possible to modify tuple, as pointed out before

TypeError: 'tuple' object does not support item assignment

In [39]:
x_reshape.shape, x_reshape.ndim, x_reshape.T #shape, number of dimensions, tranpose matrix

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [40]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [41]:
x**2

array([25,  4,  9, 16, 25, 36])

In [42]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [43]:
np.random.normal()

-0.5100997083869098

In [44]:
np.random.normal?

In [46]:
#loc, scale, size can be called keyword arguments or simply arguments

In [47]:
x = np.random.normal(size=50)
x

array([-0.97032293,  0.12110588, -0.07961985,  1.36824091,  2.3027304 ,
       -0.06703612,  0.84014567,  0.49475616, -2.12529506,  0.35356841,
       -1.43601081, -1.20252667,  0.38272558, -0.34791859,  1.28882637,
        0.16972544, -1.59148634, -0.8194687 ,  0.06058221,  0.88737492,
        0.30683026,  0.13586288, -1.02939895, -0.08869486, -0.83639858,
       -1.90221493, -2.14737471,  0.11731768, -1.37662352, -1.06842674,
       -0.28949429, -2.03169951,  0.4344778 ,  0.32419016, -1.81170117,
        0.3176389 , -1.63951713, -0.7124626 ,  0.44996503,  2.22628445,
       -0.99688047,  0.62541588, -1.45234629, -1.18498888,  1.6497225 ,
       -0.92642916, -0.08451574,  0.00437208, -0.30071471,  1.70737614])

In [48]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [49]:
np.corrcoef(x,y)

array([[1.        , 0.75016749],
       [0.75016749, 1.        ]])

In [51]:
z = np.random.normal(size=50)

In [54]:
np.corrcoef((x,y,z))

array([[ 1.        ,  0.75016749, -0.17081416],
       [ 0.75016749,  1.        , -0.01913965],
       [-0.17081416, -0.01913965,  1.        ]])

In [55]:
#np.corrocef of a tuple (a1, a2, ..., an) is nxn matrix where the entry ij is
#the correlation between ai and aj, thats why the main diagonal is made of 1s.

In [56]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[ 8.9953104  -3.84306428]
[-0.2209359  -3.23410924]


In [58]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))

rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

#the second time we use it, it changes
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]
[-10.15364596   1.13406146]


In [60]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [62]:
np.var(y), y.var(), np.mean((y-y.mean())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [63]:
X = rng.standard_normal((10,3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [64]:
X.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [66]:
X.mean(axis=0).shape

(3,)

In [65]:
X.mean(axis=1)

array([-0.13604387, -0.70466596,  0.40038349,  0.45675943, -0.04765406,
        0.73533095, -0.04256834,  0.39038958, -0.68884708, -0.53565259])

In [67]:
X.mean(axis=1).shape

(10,)